namespace Lumos.AI;

/// Streaming event emitted by an AI agent client.
public abstract record AgentStreamEvent
{
    /// A chunk of text generated by the model.
    public sealed record TextDelta(string Text) : AgentStreamEvent;

    /// A complete tool call ready for execution.
    public sealed record ToolUseComplete(string Id, string Name, string InputJson) : AgentStreamEvent;

    /// The model has finished this turn.
    public sealed record MessageStop(StopReason Reason) : AgentStreamEvent;
}

public enum StopReason
{
    EndTurn,
    ToolUse,
    MaxTokens,
    StopSequence,
    Other,
}
